var textos_EN = {

	// textos titulos generales
	'text_titulo_app': 'ET2 UI Interface',
	'text_titulo_menu': 'Menu Options',
	'text_titulo_pie': 'Footer',
	'label_seleccioncolumnas': 'Select columns',

	// textos menu
	'text_menu_persona': 'Manage person',

	//errores acciones
	'RECORDSET_VACIO': 'No matches found for the search',
	'dni_es_nulo_KO': 'DNI cannot be empty',
	'admin_no_se_puede_modificar_KO': 'Admin cannot be modified',

	//acciones
	'EDIT': 'edit',
	'DELETE': 'delete',
	'SHOWCURRENT': 'view more',

	//alumnograduacion
	'menu_alumnograduacion': 'Manage graduate student',

	// textos entidad alumnograduacion
	'text_titulo_page_alumnograduacion': 'Graduate Student Data Management',
	'text_contenido_titulo_form_alumnograduacion_ADD': 'Graduate Student Data Add Form',
	'text_contenido_titulo_form_alumnograduacion_EDIT': 'Graduate Student Data Edit Form',
	'text_contenido_titulo_form_alumnograduacion_DELETE': 'Graduate Student Data Delete Form',
	'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Graduate Student Data Detail Form',
	'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Graduate Student Data Search Form',

	// atributos
	'alumnograduacion_login': 'login',
	'alumnograduacion_password': 'password',
	'alumnograduacion_nombre': 'student first name',
	'alumnograduacion_apellidos': 'student last name',
	'alumnograduacion_titulacion': 'student degree',
	'alumnograduacion_dni': 'student DNI',
	'alumnograduacion_telefono': 'student phone',
	'alumnograduacion_email': 'student email',
	'alumnograduacion_fotoacto': 'student photo filename',
	'alumnograduacion_direccion': 'student address',

	//labels
	'label_alumnograduacion_login': 'login',
	'label_alumnograduacion_password': 'password',
	'label_alumnograduacion_nombre': 'student first name',
	'label_alumnograduacion_apellidos': 'student last name',
	'label_alumnograduacion_titulacion': 'student degree',
	'label_alumnograduacion_dni': 'student DNI',
	'label_alumnograduacion_telefono': 'student phone',
	'label_alumnograduacion_email': 'student email',
	'label_alumnograduacion_fotoacto': 'student photo filename',
	'label_alumnograduacion_direccion': 'student address',

	//errores
	'alumnograduacion_login_vacio_KO': 'Field required',
	'alumnograduacion_login_format_KO': 'No ñ, spaces, or accents allowed.',
	'alumnograduacion_login_min_size_KO': 'Minimum 4 characters.',
	'alumnograduacion_login_max_size_KO': 'Maximum 15 characters.',
	'alumnograduacion_password_vacio_KO': 'Field required',
	'alumnograduacion_password_min_size_KO': 'Minimum 8 characters.',
	'alumnograduacion_password_max_size_KO': 'Maximum 64 characters.',
	'alumnograduacion_password_format_KO': 'No ñ or accents allowed.',
	'alumnograduacion_nombre_vacio_KO': 'Field required',
	'alumnograduacion_nombre_format_KO': 'Only alphabetic characters, spaces, ñ, and accents allowed.',
	'alumnograduacion_nombre_min_size_KO': 'Minimum 2 characters.',
	'alumnograduacion_nombre_max_size_KO': 'Maximum 25 characters.',
	'alumnograduacion_apellidos_vacio_KO': 'Field required',
	'alumnograduacion_apellidos_format_KO': 'Only alphabetic characters, spaces, ñ, and accents allowed.',
	'alumnograduacion_apellidos_min_size_KO': 'Minimum 2 characters.',
	'alumnograduacion_apellidos_max_size_KO': 'Maximum 35 characters.',
	'alumnograduacion_titulacion_vacio_KO': 'Field required',
	'alumnograduacion_titulacion_format_KO': 'Only ["GREI","GRIA","MEI","MIA","PCEO"] allowed.',
	'alumnograduacion_dni_vacio_KO': 'Field required',
	'alumnograduacion_dni_format_KO': 'Format must be 8 digits and a corresponding uppercase letter.',
	'alumnograduacion_dni_max_size_KO': 'Maximum 9 characters.',
	'alumnograduacion_telefono_vacio_KO': 'Field required',
	'alumnograduacion_telefono_max_size_KO': 'Maximum 9 characters.',
	'alumnograduacion_telefono_format_KO': 'Only numbers allowed.',
	'alumnograduacion_telefono_min_size_KO': 'Minimum 9 characters.',
	'alumnograduacion_direccion_vacio_KO': 'Field required',
	'alumnograduacion_direccion_format_KO': 'Only alphabetic characters, spaces, ñ, and accents allowed.',
	'alumnograduacion_direccion_min_size_KO': 'Minimum 2 characters.',
	'alumnograduacion_direccion_max_size_KO': 'Maximum 100 characters.',
	'alumnograduacion_email_vacio_KO': 'Field required',
	'alumnograduacion_email_max_size_KO': 'Maximum 40 characters.',
	'alumnograduacion_email_format_KO': 'Must be a valid email format.',
	'nuevo_alumnograduacion_fotoacto_vacio_KO': 'Field required',
	'nuevo_alumnograduacion_fotoacto_nombrefoto_format_KO': 'Filename must be alphabetic, no spaces, ñ, or accents.',
	'nuevo_alumnograduacion_fotoacto_nombrefoto_min_size_KO': 'Minimum 7 characters.',
	'nuevo_alumnograduacion_fotoacto_nombrefoto_max_size_KO': 'Maximum 40 characters.',
	'nuevo_alumnograduacion_fotoacto_format_KO': 'Must be jpg format.',
	'nuevo_alumnograduacion_fotoacto_max_size_KO': 'Maximum size allowed is 2MB.',
	'alumnograduacion_fotoacto_nombrefoto_format_KO': 'Filename must be alphabetic, no spaces, ñ, or accents.',
	'alumnograduacion_fotoacto_nombrefoto_max_size_KO': 'Maximum 40 characters.',

	//------------------------------------------------------------------------------------------
	'menu_articulo': 'Manage articles',
	'text_titulo_page_articulo': 'Article Data Management',
	'text_contenido_titulo_form_articulo_ADD': 'Article Data Add Form',
	'text_contenido_titulo_form_articulo_EDIT': 'Article Data Edit Form',
	'text_contenido_titulo_form_articulo_DELETE': 'Article Data Delete Form',
	'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Article Data Detail Form',
	'text_contenido_titulo_form_articulo_SEARCH': 'Article Data Search Form',

	'CodigoA': 'article code',
	'AutoresA': 'article authors',
	'TituloA': 'article title',
	'TituloR': 'journal title',
	'ISSN': 'ISSN',
	'VolumenR': 'journal volume',
	'PagIniA': 'article start page',
	'PagFinA': 'article end page',
	'FechaPublicacionR': 'journal publication date',
	'FicheropdfA': 'article PDF file',
	'nuevo_FicheropdfA': 'new article PDF file',
	'EstadoA': 'article status',

	'label_CodigoA': 'article code',
	'label_AutoresA': 'article authors',
	'label_TituloA': 'article title',
	'label_TituloR': 'journal title',
	'label_ISSN': 'ISSN',
	'label_VolumenR': 'journal volume',
	'label_PagIniA': 'article start page',
	'label_PagFinA': 'article end page',
	'label_FechaPublicacionR': 'journal publication date',
	'label_FicheropdfA': 'article PDF file',
	'label_nuevo_FicheropdfA': 'new article PDF file',
	'label_EstadoA': 'article status',

	//sek 
	'Enviado': 'Sent',
	'Revision': 'Review',
	'Publicado': 'Published',

	'FechaPublicacionR_vacio_KO': 'Publication date cannot be empty.',
	'FechaPublicacionR_format_KO': 'Date format must be YYYY-MM-DD.',
	'FechaPublicacionR_superiorActual_KO': 'Publication date cannot be in the future.',
	'FechaPublicacionR_correcto_OK': 'Valid publication date.',
	'FechaPublicacionR_vacio_OK': 'Empty field allowed in search.',
	'CodigoA_format_KO': 'Only numbers allowed.',
	'CodigoA_max_size_KO': 'Maximum 11 characters.',
	'AutoresA_vacio_KO': 'Field required',
	'AutoresA_min_size_KO': 'Minimum 4 characters.',
	'AutoresA_max_size_KO': 'Maximum 200 characters.',
	'AutoresA_format_KO': 'Numbers not allowed.',
	'AutoresA_format_KO': 'No ñ, spaces, or accents allowed.',
	'TituloA_vacio_KO': 'Field required',
	'TituloA_format_KO': 'Only alphabetic characters, spaces, ñ, and accents allowed.',
	'TituloA_min_size_KO': 'Minimum 2 characters.',
	'TituloA_max_size_KO': 'Maximum 100 characters.',
	'TituloR_vacio_KO': 'Field required',
	'TituloR_format_KO': 'Only alphabetic characters, spaces, ñ, and accents allowed.',
	'TituloR_min_size_KO': 'Minimum 2 characters.',
	'TituloR_max_size_KO': 'Maximum 100 characters.',
	'EstadoA_vacio_KO': 'Field required',
	'EstadoA_format_KO': 'Only [Sent, Review, Published] allowed.',
	'ISSN_vacio_KO': 'Field required',
	'ISSN_format_KO': 'Format must be 8 digits or 7 digits and a corresponding uppercase X.',
	'ISSN_max_size_KO': 'Exactly 9 characters.',
	'VolumenR_vacio_KO': 'Field required',
	'VolumenR_max_size_KO': 'Maximum 4 characters.',
	'VolumenR_format_KO': 'Only numbers allowed.',
	'PagIniA_vacio_KO': 'Field required',
	'PagIniA_format_KO': 'Only numbers allowed.',
	'PagIniA_max_size_KO': 'Maximum 4 characters.',
	'PagFinA_vacio_KO': 'Field required',
	'PagFinA_format_KO': 'Only numbers allowed.',
	'PagFinA_max_size_KO': 'Maximum 4 characters.',
	'nuevo_FicheropdfA_vacio_KO': 'Field required',
	'nuevo_FicheropdfA_nombrepdf_format_KO': 'Filename must be alphabetic, no spaces',
	'nuevo_FicheropdfA_nombrepdf_min_size_KO': 'Minimum 1 character plus extension (total 4).',
	'nuevo_FicheropdfA_nombrepdf_max_size_KO': 'Maximum 20 characters.',
	'nuevo_FicheropdfA_format_KO': 'Must be pdf format.',
	'nuevo_FicheropdfA_max_size_KO': 'Maximum size allowed is 2MB.',
	'FicheropdfA_nombrepdf_format_KO': 'Filename must be alphabetic, no spaces',
	'FicheropdfA_nombrepdf_max_size_KO': 'Maximum 20 characters.',

	//------------------------------------------------------------------------------------------
	'menu_ubicacion': 'Manage location',
	'text_titulo_page_ubicacion': 'Location Data Management',
	'text_contenido_titulo_form_ubicacion_ADD': 'Location Data Add Form',
	'text_contenido_titulo_form_ubicacion_EDIT': 'Location Data Edit Form',
	'text_contenido_titulo_form_ubicacion_DELETE': 'Location Data Delete Form',
	'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Location Data Detail Form',
	'text_contenido_titulo_form_ubicacion_SEARCH': 'Location Data Search Form',

	//atributos        
	'id_site': 'site ID',
	'site_latitud': 'site latitude',
	'site_longitud': 'site longitude',
	'site_altitude': 'site altitude',
	'site_locality': 'site locality',
	'site_provider_login': 'provider',
	'site_north_photo': 'site north photo',
	'site_south_photo': 'site south photo',
	'site_east_photo': 'site east photo',
	'site_west_photo': 'site west photo',
	'nuevo_site_north_photo': 'new site north photo',
	'nuevo_site_south_photo': 'new site south photo',
	'nuevo_site_east_photo': 'new site east photo',
	'nuevo_site_west_photo': 'new site west photo',

	'label_id_site': 'site ID',
	'label_site_latitud': 'site latitude',
	'label_site_longitud': 'site longitude',
	'label_site_altitude': 'site altitude',
	'label_site_locality': 'site locality',
	'label_site_provider_login': 'provider',
	'label_site_north_photo': 'site north photo',
	'label_site_south_photo': 'site south photo',
	'label_site_east_photo': 'site east photo',
	'label_site_west_photo': 'site west photo',
	'label_nuevo_site_north_photo': 'site north photo',
	'label_nuevo_site_south_photo': 'site south photo',
	'label_nuevo_site_east_photo': 'site east photo',
	'label_nuevo_site_west_photo': 'site west photo',

	'id_site_format_KO': 'Only numbers allowed.',
	'id_site_max_size_KO': 'Cannot exceed 11 characters.',
	'site_latitud_vacio_KO': 'Cannot be empty.',
	'site_latitud_format_KO': 'Invalid format, numbers only.',
	'site_latitud_range_KO': 'Invalid latitude.',
	'site_latitud_decimals_KO': 'Maximum 6 decimals allowed.',
	'site_longitud_vacio_KO': 'Cannot be empty.',
	'site_longitud_format_KO': 'Invalid format, numbers only.',
	'site_longitud_range_KO': 'Invalid longitude.',
	'site_longitud_decimals_KO': 'Maximum 6 decimals allowed.',
	'site_altitude_vacio_KO': 'Cannot be empty.',
	'site_altitude_format_KO': 'Invalid format, numbers only.',
	'site_altitude_min_size_KO': 'Must have at least 1 character.',
	'site_altitude_max_size_KO': 'Cannot exceed 4 characters.',
	'site_locality_vacio_KO': 'Cannot be empty.',
	'site_locality_format_KO': 'Invalid format.',
	'site_locality_min_size_KO': 'Must have at least 2 characters.',
	'site_locality_max_size_KO': 'Cannot exceed 40 characters.',
	'site_provider_login_vacio_KO': 'Cannot be empty.',
	'site_provider_login_format_KO': 'Invalid format, letters, numbers, and dashes only.',
	'site_provider_login_min_size_KO': 'Must have at least 4 characters.',
	'site_provider_login_max_size_KO': 'Cannot exceed 30 characters.',
	'nuevo_site_north_photo_vacio_KO': 'Field required',
	'nuevo_site_north_photo_nombrefoto_format_KO': 'Filename must be alphanumeric, with ñ and accents, no spaces.',
	'nuevo_site_north_photo_nombrefoto_min_size_KO': 'Minimum 1 character.',
	'nuevo_site_north_photo_nombrefoto_max_size_KO': 'Maximum 50 characters.',
	'nuevo_site_north_photo_format_KO': 'File must be an image.',
	'nuevo_site_north_photo_max_size_KO': 'Maximum size allowed is 2MB.',
	'site_north_photo_nombrefoto_format_KO': 'Filename must be alphanumeric, with ñ and accents, no spaces.',
	'site_north_photo_nombrefoto_max_size_KO': 'Maximum 50 characters.',
	'nuevo_site_south_photo_vacio_KO': 'Field required',
	'nuevo_site_south_photo_nombrefoto_format_KO': 'Filename must be alphanumeric, with ñ and accents, no spaces.',
	'nuevo_site_south_photo_nombrefoto_min_size_KO': 'Minimum 1 character.',
	'nuevo_site_south_photo_nombrefoto_max_size_KO': 'Maximum 50 characters.',
	'nuevo_site_south_photo_format_KO': 'File must be an image.',
	'nuevo_site_south_photo_max_size_KO': 'Maximum size allowed is 2MB.',
	'site_south_photo_nombrefoto_format_KO': 'Filename must be alphanumeric, with ñ and accents, no spaces.',
	'site_south_photo_nombrefoto_max_size_KO': 'Maximum 50 characters.',
	'nuevo_site_east_photo_vacio_KO': 'Field required',
	'nuevo_site_east_photo_nombrefoto_format_KO': 'Filename must be alphanumeric, with ñ and accents, no spaces.',
	'nuevo_site_east_photo_nombrefoto_min_size_KO': 'Minimum 1 character.',
	'nuevo_site_east_photo_nombrefoto_max_size_KO': 'Maximum 50 characters.',
	'nuevo_site_east_photo_format_KO': 'File must be an image.',
	'nuevo_site_east_photo_max_size_KO': 'Maximum size allowed is 2MB.',
	'site_east_photo_nombrefoto_format_KO': 'Filename must be alphanumeric, with ñ and accents, no spaces.',
	'site_east_photo_nombrefoto_max_size_KO': 'Maximum 50 characters.',
	'nuevo_site_west_photo_vacio_KO': 'Field required',
	'nuevo_site_west_photo_nombrefoto_format_KO': 'Filename must be alphanumeric, with ñ and accents, no spaces.',
	'nuevo_site_west_photo_nombrefoto_min_size_KO': 'Minimum 1 character.',
	'nuevo_site_west_photo_nombrefoto_max_size_KO': 'Maximum 50 characters.',
	'nuevo_site_west_photo_format_KO': 'File must be an image.',
	'nuevo_site_west_photo_max_size_KO': 'Maximum size allowed is 2MB.',

	'site_west_photo_nombrefoto_format_KO': 'Filename must be alphanumeric, with ñ and accents, no spaces.',
	'site_west_photo_nombrefoto_max_size_KO': 'Maximum 50 characters.',

}

