var textos_ES = {

	// textos titulos generales
	'text_titulo_app': 'Interfaz ET2 IU',
	'text_titulo_menu': 'Opciones  Menú',
	'text_titulo_pie': 'Pie de página',
	'label_seleccioncolumnas': 'Seleccionar columnas',

	// textos de test
	/*'res_estructura_tests':'Tabla verificacion estructura de test',
	'resultadodef':'formato correcto estructura definicion tests',
	'res_estructura_pruebas':'Tabla verificacion estructura de pruebas',
	'resultadoprueba':'formato correcto estructura pruebas',
	'res_pruebas':'Tabla ejecución de pruebas',
	'resultadotest':'Resultado ejecucion pruebas',
	*/

	// textos menu
	'text_menu_persona': 'Gestionar persona',


	//errores acciones
	'RECORDSET_VACIO': 'No hay coincidencias para la búsqueda',
	'dni_es_nulo_KO': 'El dni no puede ser vacio',

	'admin_no_se_puede_modificar_KO': 'El admin no se puede modificar',

	//acciones
	'EDIT': 'editar',
	'DELETE': 'eliminar',
	'SHOWCURRENT': 'ver mas',
	//alumnograduacion
	//menu
	'menu_alumnograduacion': 'Gestionar alumnograduacion',

	// textos entidad alumnograduacion
	'text_titulo_page_alumnograduacion': 'Gestión de Datos alumnograduacion',
	'text_contenido_titulo_form_alumnograduacion_ADD': 'Formulario Alta Datos alumnograduacion',
	'text_contenido_titulo_form_alumnograduacion_EDIT': 'Formulario Modificación Datos alumnograduacion',
	'text_contenido_titulo_form_alumnograduacion_DELETE': 'Formulario Eliminación Datos alumnograduacion',
	'text_contenido_titulo_form_alumnograduacion_SHOWCURRENT': 'Formulario Detalle Datos alumnograduacion',
	'text_contenido_titulo_form_alumnograduacion_SEARCH': 'Formulario Búsqueda Datos alumnograduacion',

	// atributos

	'alumnograduacion_login': 'inicio',
	'alumnograduacion_password': 'contraseña',
	'alumnograduacion_nombre': 'nombre del alumno',
	'alumnograduacion_apellidos': 'apellidos del alumno',
	'alumnograduacion_titulacion': 'titulacion del alumno',
	'alumnograduacion_dni': 'dni del alumno',
	'alumnograduacion_telefono': 'telefono del alumno',
	'alumnograduacion_email': 'correo del alumno',
	'alumnograduacion_fotoacto': 'nombre de la foto del alumno',
	'alumnograduacion_direccion': 'direccion del alumno',

	//labels
	'label_alumnograduacion_login': 'inicio',
	'label_alumnograduacion_password': 'contraseña',
	'label_alumnograduacion_nombre': 'nombre del alumno',
	'label_alumnograduacion_apellidos': 'apellidos del alumno',
	'label_alumnograduacion_titulacion': 'titulacion del alumno',
	'label_alumnograduacion_dni': 'dni del alumno',
	'label_alumnograduacion_telefono': 'telefono del alumno',
	'label_alumnograduacion_email': 'correo del alumno',
	'label_alumnograduacion_fotoacto': 'nombre de la foto del alumno',
	'label_alumnograduacion_direccion': 'direccion del alumno',

	//errores
	'alumnograduacion_login_vacio_KO': 'Complete el campo',
	'alumnograduacion_login_format_KO': 'No se admiten ni ñ, ni espacios, ni acentos.',
	'alumnograduacion_login_min_size_KO': 'Mínimo 4 caracteres.',
	'alumnograduacion_login_max_size_KO': 'Máximo 15 caracteres.',
	'alumnograduacion_password_vacio_KO': 'Complete el campo',
	'alumnograduacion_password_min_size_KO': 'Mínimo 8 caracteres.',
	'alumnograduacion_password_max_size_KO': 'Máximo 64 caracteres.',
	'alumnograduacion_password_format_KO': 'No debe contener ni ñ ni acentos.',
	'alumnograduacion_nombre_vacio_KO': 'Complete el campo',
	'alumnograduacion_nombre_format_KO': 'No se admiten caracteres que no sean alfabeticos, espacios, ñ o acentos.',
	'alumnograduacion_nombre_min_size_KO': 'Mínimo 2 caracteres.',
	'alumnograduacion_nombre_max_size_KO': 'Máximo 25 caracteres.',
	'alumnograduacion_apellidos_vacio_KO': 'Complete el campo',
	'alumnograduacion_apellidos_format_KO': 'No se admiten caracteres que no sean alfabeticos, espacios, ñ o acentos.',
	'alumnograduacion_apellidos_min_size_KO': 'Mínimo 2 caracteres.',
	'alumnograduacion_apellidos_max_size_KO': 'Máximo 35 caracteres.',
	'alumnograduacion_titulacion_vacio_KO': 'Complete el campo',
	'alumnograduacion_titulacion_format_KO': 'No se admiten otros valores que no sean ["GREI","GRIA","MEI","MIA","PCEO"].',
	'alumnograduacion_dni_vacio_KO': 'Complete el campo',
	'alumnograduacion_dni_format_KO': 'El format debe ser 8 dígitos y una letra mayúscula que corresponda al numero.',
	'alumnograduacion_dni_max_size_KO': 'Máximo 9 caracteres.',
	'alumnograduacion_telefono_vacio_KO': 'Complete el campo',
	'alumnograduacion_telefono_max_size_KO': 'Máximo 9 caracteres.',
	'alumnograduacion_telefono_format_KO': 'Solo se admiten números.',
	'alumnograduacion_telefono_min_size_KO': 'Mínimo 9 caracteres.',
	'alumnograduacion_direccion_vacio_KO': 'Complete el campo',
	'alumnograduacion_direccion_format_KO': 'No se admiten caracteres que no sean alfabeticos, espacios, ñ o acentos.',
	'alumnograduacion_direccion_min_size_KO': 'Mínimo 2 caracteres.',
	'alumnograduacion_direccion_max_size_KO': 'Máximo 100 caracteres.',
	'alumnograduacion_email_vacio_KO': 'Complete el campo',
	'alumnograduacion_email_max_size_KO': 'Máximo 40 caracteres.',
	'alumnograduacion_email_format_KO': 'El format debe ser email válido.',
	'nuevo_alumnograduacion_fotoacto_vacio_KO': 'Complete el campo',
	'nuevo_alumnograduacion_fotoacto_nombrefoto_format_KO': 'El format deben ser alfabeticos sin acentos, ñ ni espacios.',
	'nuevo_alumnograduacion_fotoacto_nombrefoto_min_size_KO': 'El nombre debe contener minimo de 7 caracteres.',
	'nuevo_alumnograduacion_fotoacto_nombrefoto_max_size_KO': 'El nombre debe contener maximo de 40 caracteres.',
	'nuevo_alumnograduacion_fotoacto_format_KO': 'El format debe ser jpg.',
	'nuevo_alumnograduacion_fotoacto_max_size_KO': 'El tamaño máximo permitido es 2MB.',
	'alumnograduacion_fotoacto_nombrefoto_format_KO': 'El format deben ser alfabeticos sin acentos, ñ ni espacios.',
	'alumnograduacion_fotoacto_nombrefoto_max_size_KO': 'El nombre debe contener maximo de 40 caracteres.',

	//------------------------------------------------------------------------------------------
	'menu_articulo': 'Gestionar articulos',
	'text_titulo_page_articulo': 'Gestión de Datos articulos',
	'text_contenido_titulo_form_articulo_ADD': 'Formulario Alta Datos articulo',
	'text_contenido_titulo_form_articulo_EDIT': 'Formulario Modificación Datos articulo',
	'text_contenido_titulo_form_articulo_DELETE': 'Formulario Eliminación Datos articulo',
	'text_contenido_titulo_form_articulo_SHOWCURRENT': 'Formulario Detalle Datos articulo',
	'text_contenido_titulo_form_articulo_SEARCH': 'Formulario Búsqueda Datos articulo',


	'CodigoA': 'código articulo',
	'AutoresA': 'autores del articulo',
	'TituloA': 'título del artículo',
	'TituloR': 'título de la revista',
	'ISSN': 'ISSN',
	'VolumenR': 'volumen de la revista',
	'PagIniA': 'página inicial del articulo',
	'PagFinA': 'página final  del articulo',
	'FechaPublicacionR': 'fecha de publicación de la revista',
	'FicheropdfA': 'archivo PDF del articulo',
	'nuevo_FicheropdfA': 'nuevo archivo PDF del articulo',
	'EstadoA': 'estado articulo',

	'label_CodigoA': 'código articulo',
	'label_AutoresA': 'autores articulo',
	'label_TituloA': 'título del artículo',
	'label_TituloR': 'título de la revista',
	'label_ISSN': 'ISSN',
	'label_VolumenR': 'volumen revista',
	'label_PagIniA': 'página inicial articulo',
	'label_PagFinA': 'página final articulo',
	'label_FechaPublicacionR': 'fecha de publicación revista',
	'label_FicheropdfA': 'archivo PDF articulo',
	'label_nuevo_FicheropdfA': 'nuevo archivo PDF articulo',
	'label_EstadoA': 'estado articulo',

	//sek 
	'Enviado': 'Enviado',
	'Revision': 'Revision',
	'Publicado': 'Publicado',

	'FechaPublicacionR_vacio_KO': 'La fecha de publicación no puede estar vacía.',
	'FechaPublicacionR_format_KO': 'El formato de la fecha debe ser YYYY-MM-DD.',
	'FechaPublicacionR_superiorActual_KO': 'La fecha de publicación no puede ser posterior a la fecha actual.',
	'FechaPublicacionR_correcto_OK': 'Fecha de publicación válida.',
	'FechaPublicacionR_vacio_OK': 'Campo vacío permitido en búsqueda.',
	'CodigoA_format_KO': 'Solo se admiten números.',
	'CodigoA_max_size_KO': 'Maximo 11 caracteres.',
	'AutoresA_vacio_KO': 'Complete el campo',
	'AutoresA_min_size_KO': 'Mínimo 4 caracteres.',
	'AutoresA_max_size_KO': 'Máximo 200 caracteres.',
	'AutoresA_format_KO': 'No debe contener números.',
	'AutoresA_format_KO': 'No se admiten ni ñ, ni espacios, ni acentos.',
	'TituloA_vacio_KO': 'Complete el campo',
	'TituloA_format_KO': 'No se admiten caracteres que no sean alfabeticos, espacios, ñ o acentos.',
	'TituloA_min_size_KO': 'Mínimo 2 caracteres.',
	'TituloA_max_size_KO': 'Máximo 100 caracteres.',
	'TituloR_vacio_KO': 'Complete el campo',
	'TituloR_format_KO': 'No se admiten caracteres que no sean alfabeticos, espacios, ñ o acentos.',
	'TituloR_min_size_KO': 'Mínimo 2 caracteres.',
	'TituloR_max_size_KO': 'Máximo 100 caracteres.',
	'EstadoA_vacio_KO': 'Complete el campo',
	'EstadoA_format_KO': 'No se admiten otros valores que no sean [Enviado,Revision,Publicado].',
	'EstadoA_format_KO': 'No se admiten otros valores que no sean [Enviado,Revision,Publicado] o subexpresiones del mismo.',
	'ISSN_vacio_KO': 'Complete el campo',
	'ISSN_format_KO': 'El format debe ser 8 dígitos o 7 digitos y una letra X mayúscula que corresponda al numero anterior.',
	'ISSN_max_size_KO': 'Máximo y mínimo 9 caracteres.',
	'ISSN_max_size_KO': 'Maximo 9 caracteres.',
	'VolumenR_vacio_KO': 'Complete el campo',
	'VolumenR_max_size_KO': 'Máximo 4 caracteres.',
	'VolumenR_format_KO': 'Solo se admiten números.',
	'PagIniA_vacio_KO': 'Complete el campo',
	'PagIniA_format_KO': 'No se admiten caracteres que no números.',
	'PagIniA_max_size_KO': 'Máximo 4 caracteres.',
	'PagIniA_max_size_KO': 'Máximo 4 caracteres.',
	'PagFinA_vacio_KO': 'Complete el campo',
	'PagFinA_format_KO': 'No se admiten caracteres que no números.',
	'PagFinA_max_size_KO': 'Máximo 4 caracteres.',
	'nuevo_FicheropdfA_vacio_KO': 'Complete el campo',
	'nuevo_FicheropdfA_nombrepdf_format_KO': 'El format deben ser alfabeticos sin espacios',
	'nuevo_FicheropdfA_nombrepdf_min_size_KO': 'El nombre debe contener minimo de 1 caracter mas la extension (total 4).',
	'nuevo_FicheropdfA_nombrepdf_max_size_KO': 'El nombre debe contener maximo de 20 caracteres.',
	'nuevo_FicheropdfA_format_KO': 'El format debe ser pdf.',
	'nuevo_FicheropdfA_max_size_KO': 'El tamaño máximo permitido es 2MB.',
	'FicheropdfA_nombrepdf_format_KO': 'El format deben ser alfabeticos sin espacios',
	'FicheropdfA_nombrepdf_max_size_KO': 'El nombre debe contener maximo de 20 caracteres.',

	//------------------------------------------------------------------------------------------

	'menu_ubicacion': 'Gestionar ubicacion',
	'text_titulo_page_ubicacion': 'Gestión de Datos ubicacion',
	'text_contenido_titulo_form_ubicacion_ADD': 'Formulario Alta Datos ubicacion',
	'text_contenido_titulo_form_ubicacion_EDIT': 'Formulario Modificación Datos ubicacion',
	'text_contenido_titulo_form_ubicacion_DELETE': 'Formulario Eliminación Datos ubicacion',
	'text_contenido_titulo_form_ubicacion_SHOWCURRENT': 'Formulario Detalle Datos ubicacion',
	'text_contenido_titulo_form_ubicacion_SEARCH': 'Formulario Búsqueda Datos ubicacion',
	//atributos        
	'id_site': 'identificacion del sitio',
	'site_latitud': 'latitud  del sitio',
	'site_longitud': 'longitud  del sitio',
	'site_altitude': 'altitud  del sitio',
	'site_locality': 'localidad  del sitio',
	'site_provider_login': 'proveedor',
	'site_north_photo': 'foto norte  del sitio',
	'site_south_photo': 'foto sur  del sitio',
	'site_east_photo': 'foto este  del sitio',
	'site_west_photo': 'foto oeste del sitio',
	'nuevo_site_north_photo': 'nueva foto norte  del sitio',
	'nuevo_site_south_photo': 'nueva foto sur  del sitio',
	'nuevo_site_east_photo': 'nueva foto este del sitio',
	'nuevo_site_west_photo': 'nueva foto oeste del sitio',

	'label_id_site': 'identificacion del sitio',
	'label_site_latitud': 'latitud  del sitio',
	'label_site_longitud': 'longitud del sitio',
	'label_site_altitude': 'altitud del sitio',
	'label_site_locality': 'localidad del sitio',
	'label_site_provider_login': 'proveedor',
	'label_site_north_photo': 'foto norte del sitio',
	'label_site_south_photo': 'foto sur del sitio',
	'label_site_east_photo': 'foto este del sitio',
	'label_site_west_photo': 'foto oeste del sitio',
	'label_nuevo_site_north_photo': 'foto norte del sitio',
	'label_nuevo_site_south_photo': 'foto sur del sitio',
	'label_nuevo_site_east_photo': 'foto este del sitio',
	'label_nuevo_site_west_photo': 'foto oeste del sitio',

	'id_site_format_KO': 'Solo se admiten números.',
	'id_site_max_size_KO': 'No puede superar 11 caracteres.',
	'site_latitud_vacio_KO': 'No puede estar vacío.',
	'site_latitud_format_KO': 'Formato inválido, solo números.',
	'site_latitud_range_KO': 'Latitud inválida.',
	'site_latitud_decimals_KO': 'Máximo 6 decimales permitidos.',
	'site_longitud_vacio_KO': 'No puede estar vacío.',
	'site_longitud_format_KO': 'Formato inválido, solo números.',
	'site_longitud_range_KO': 'Longitud inválida.',
	'site_longitud_decimals_KO': 'Máximo 6 decimales permitidos.',
	'site_altitude_vacio_KO': 'No puede estar vacío.',
	'site_altitude_format_KO': 'Formato inválido, solo números.',
	'site_altitude_min_size_KO': 'Debe tener al menos 1 carácter.',
	'site_altitude_max_size_KO': 'No puede superar 4 caracteres.',
	'site_locality_vacio_KO': 'No puede estar vacío.',
	'site_locality_format_KO': 'Formato inválido.',
	'site_locality_min_size_KO': 'Debe tener al menos 2 caracteres.',
	'site_locality_max_size_KO': 'No puede superar 40 caracteres.',
	'site_provider_login_vacio_KO': 'No puede estar vacío.',
	'site_provider_login_format_KO': 'Formato inválido, solo letras, números y guiones.',
	'site_provider_login_min_size_KO': 'Debe tener al menos 4 caracteres.',
	'site_provider_login_max_size_KO': 'No puede superar 30 caracteres.',
	'nuevo_site_north_photo_vacio_KO': 'Complete el campo',
	'nuevo_site_north_photo_nombrefoto_format_KO': 'El formato debe ser alfanumérico, con ñ y acentos, sin espacios.',
	'nuevo_site_north_photo_nombrefoto_min_size_KO': 'El nombre debe contener mínimo 1 carácter.',
	'nuevo_site_north_photo_nombrefoto_max_size_KO': 'El nombre debe contener máximo 50 caracteres.',
	'nuevo_site_north_photo_format_KO': 'El fichero debe ser imagen.',
	'nuevo_site_north_photo_max_size_KO': 'El tamaño máximo permitido es 2MB.',
	'site_north_photo_nombrefoto_format_KO': 'El formato debe ser alfanumérico, con ñ y acentos, sin espacios.',
	'site_north_photo_nombrefoto_max_size_KO': 'El nombre debe contener máximo 50 caracteres.',
	'nuevo_site_south_photo_vacio_KO': 'Complete el campo',
	'nuevo_site_south_photo_nombrefoto_format_KO': 'El formato debe ser alfanumérico, con ñ y acentos, sin espacios.',
	'nuevo_site_south_photo_nombrefoto_min_size_KO': 'El nombre debe contener mínimo 1 carácter.',
	'nuevo_site_south_photo_nombrefoto_max_size_KO': 'El nombre debe contener máximo 50 caracteres.',
	'nuevo_site_south_photo_format_KO': 'El fichero debe ser imagen.',
	'nuevo_site_south_photo_max_size_KO': 'El tamaño máximo permitido es 2MB.',
	'site_south_photo_nombrefoto_format_KO': 'El formato debe ser alfanumérico, con ñ y acentos, sin espacios.',
	'site_south_photo_nombrefoto_max_size_KO': 'El nombre debe contener máximo 50 caracteres.',
	'nuevo_site_east_photo_vacio_KO': 'Complete el campo',
	'nuevo_site_east_photo_nombrefoto_format_KO': 'El formato debe ser alfanumérico, con ñ y acentos, sin espacios.',
	'nuevo_site_east_photo_nombrefoto_min_size_KO': 'El nombre debe contener mínimo 1 carácter.',
	'nuevo_site_east_photo_nombrefoto_max_size_KO': 'El nombre debe contener máximo 50 caracteres.',
	'nuevo_site_east_photo_format_KO': 'El fichero debe ser imagen.',
	'nuevo_site_east_photo_max_size_KO': 'El tamaño máximo permitido es 2MB.',
	'site_east_photo_nombrefoto_format_KO': 'El formato debe ser alfanumérico, con ñ y acentos, sin espacios.',
	'site_east_photo_nombrefoto_max_size_KO': 'El nombre debe contener máximo 50 caracteres.',
	'nuevo_site_west_photo_vacio_KO': 'Complete el campo',
	'nuevo_site_west_photo_nombrefoto_format_KO': 'El formato debe ser alfanumérico, con ñ y acentos, sin espacios.',
	'nuevo_site_west_photo_nombrefoto_min_size_KO': 'El nombre debe contener mínimo 1 carácter.',
	'nuevo_site_west_photo_nombrefoto_max_size_KO': 'El nombre debe contener máximo 50 caracteres.',
	'nuevo_site_west_photo_format_KO': 'El fichero debe ser imagen.',
	'nuevo_site_west_photo_max_size_KO': 'El tamaño máximo permitido es 2MB.',
	'site_west_photo_nombrefoto_format_KO': 'El formato debe ser alfanumérico, con ñ y acentos, sin espacios.',
	'site_west_photo_nombrefoto_max_size_KO': 'El nombre debe contener máximo 50 caracteres.',

}